// Public, fictional POC fixtures. These are intentionally not production credentials.
// This adapter has the same asynchronous boundary a future HTTP API client will use.
export const DEMO_ACCOUNTS = Object.freeze([
  { id: 'user-member', email: 'member@tga.co.za', password: 'demo123', name: 'Anele Dlamini', role: 'member', memberId: 'TGA-2026-1048', label: 'Active member' },
  { id: 'user-pending', email: 'pending@tga.example', password: 'demo123', name: 'Megan Jacobs', role: 'member', memberId: 'TGA-2026-1047', label: 'Pending applicant' },
  { id: 'user-expired', email: 'expired@tga.example', password: 'demo123', name: 'Thandiwe Ncube', role: 'member', memberId: 'TGA-2026-1043', label: 'Expired member' },
  { id: 'user-admin', email: 'admin@tga.co.za', password: 'admin123', name: 'TGA Administrator', role: 'admin', label: 'System administrator' },
  { id: 'user-membership', email: 'membership@tga.example', password: 'demo123', name: 'Demo Membership Administrator', role: 'membership', label: 'Membership administrator' },
  { id: 'user-verifier', email: 'verifier@tga.example', password: 'demo123', name: 'Demo Document Verifier', role: 'verifier', label: 'Document verifier' },
  { id: 'user-finance', email: 'finance@tga.example', password: 'demo123', name: 'Demo Finance User', role: 'finance', label: 'Finance user' },
  { id: 'user-assessor', email: 'assessor@tga.example', password: 'demo123', name: 'Demo Assessor', role: 'assessor', label: 'Assessment administrator' },
  { id: 'user-support', email: 'support@tga.example', password: 'demo123', name: 'Demo Support Agent', role: 'support', label: 'Support agent' }
]);
export const ROLE_SECTIONS = Object.freeze({ member: ['overview','documents','assessments','payments','profile'], admin: ['dashboard','members','reviews','assessments','payments','audit','notifications','demo'], membership: ['dashboard','members','notifications'], verifier: ['reviews','notifications'], finance: ['payments','notifications'], assessor: ['assessments','notifications'], support: ['members','notifications'] });
export const STORE_KEY = 'tga-poc-v2';
export const SESSION_KEY = 'tga-poc-session-v2';
export const DEMO_PASSWORD = 'demo123';
const clone = value => structuredClone(value);
export const addMonths = (value, months = 12) => {
  const date = new Date(value); const day = date.getUTCDate();
  date.setUTCDate(1); date.setUTCMonth(date.getUTCMonth() + months);
  const last = new Date(Date.UTC(date.getUTCFullYear(), date.getUTCMonth()+1, 0)).getUTCDate();
  date.setUTCDate(Math.min(day, last)); return date.toISOString();
};
const offset = (now, days) => new Date(new Date(now).getTime()+days*86400000).toISOString();
const known = [
  ['TGA-2026-1048','Anele','Dlamini','Professional','Active','Gauteng'],
  ['TGA-2026-1047','Megan','Jacobs','Annual','Pending review','Western Cape'],
  ['TGA-2026-1046','Thabo','Mokoena','Professional','Active','Limpopo'],
  ['TGA-2026-1045','Candice','Naidoo','Annual','Payment due','KwaZulu-Natal'],
  ['TGA-2026-1044','Bongani','Khumalo','Annual','Active','Mpumalanga'],
  ['TGA-2026-1043','Thandiwe','Ncube','Professional','Expired','Free State']
];
const templates = ['registration-received','email-verification','password-reset','membership-approved','membership-rejected','document-received','document-approved','document-rejected','membership-expiring','membership-expired','payment-successful','payment-failed','assessment-result','support-request'];
const makeQuestions = suffix => [
  ['Which data belongs in this demonstration?', ['Real identity documents','Fictional sample data only','Bank card numbers'],1],
  ['What happens during a mock payment?', ['A real bank transfer','A recorded simulation with no money moved','A firearm licence is issued'],1],
  ['Who reviews a pending demo document?', ['Any member','A document verifier','An anonymous visitor'],1],
  ['Where can you view a payment result?', ['Payment history','Your bank statement','An unrelated website'],0],
  ['Does this exercise confer accreditation?', ['Yes','No, it is a demo learning check','Only after two attempts'],1]
].map(([text, options, correct], i) => ({ id:`${suffix}-q${i}`, text, options, correct, points:1 }));
export function seedDemo(now = new Date().toISOString()) {
  const members = Array.from({length:50}, (_,i) => {
    const [id,firstName,lastName,plan,status,province] = known[i] || [`TGA-2026-${1042-(i-6)}`,'Demo',`Member ${String(i+1).padStart(2,'0')}`,i%2?'Annual':'Professional',['Active','Pending review','Active','Expired','Suspended'][i%5],'Gauteng'];
    const endDate = status==='Pending review' ? null : offset(now,status==='Expired'?-15:i===0?21:100+i);
    return { id,firstName,lastName,name:`${firstName} ${lastName}`,email:`demo.member${i+1}@example.com`,mobile:'000 000 0000',province,city:'Demo city',postalCode:'0000',address:'Fictional demonstration address only',communication:'Email',plan,status,startDate:endDate?addMonths(endDate,-12):null,endDate,createdUtc:offset(now,-30+i/10) };
  });
  const plans=[{id:'annual',name:'Annual',annualFee:450,joiningFee:0,durationMonths:12},{id:'professional',name:'Professional',annualFee:750,joiningFee:0,durationMonths:12}];
  const documentTypes=['Identity','Address','Compliance','Profile','Other'].map(name=>({id:name,name,required:false,maxSize:5*1024*1024,mimeTypes:['application/pdf','image/jpeg','image/png']}));
  const documents=Array.from({length:64},(_,i)=>({id:`doc-${i+1}`,memberId:members[i<4?0:1+(i-4)%49].id,name:i<4?['Demo identity document.pdf','Demo proof of address.pdf','Demo supporting certificate.pdf','Demo profile photograph.jpg'][i]:`Demo supporting record ${i+1}.pdf`,type:documentTypes[i%5].name,date:offset(now,-10+i/100),status:i===2?'In review':['Approved','Approved','In review','Rejected'][i%4],sizeBytes:1000+i*25,mime:i===3?'image/jpeg':'application/pdf',expiryDate:null,reason:i%4===3?'Demo: please provide a clearer sample.':'',metadataOnly:true}));
  const assessments=[{id:'portal-foundation',title:'Demo Portal Foundation',description:'Five fictional portal-learning questions. No accreditation or competency is awarded.',passMark:80,maxAttempts:3,timeLimitMinutes:null,active:true,questions:makeQuestions('portal')},{id:'member-records',title:'Demo Member Records',description:'A second fictional practice assessment.',passMark:80,maxAttempts:3,timeLimitMinutes:null,active:true,questions:makeQuestions('records')}];
  const attempts=Array.from({length:24},(_,i)=>({id:`attempt-${i+1}`,memberId:members[i].id,assessmentId:assessments[i%2].id,title:assessments[i%2].title,startedUtc:offset(now,-8),submittedUtc:offset(now,-8),percentage:i%5===0?60:100,passed:i%5!==0,status:i%5===0?'Failed':'Passed',passMark:80}));
  const payments=Array.from({length:40},(_,i)=>({id:`payment-${i+1}`,memberId:members[i].id,reference:`TGA-MOCK-${String(2841-i).padStart(6,'0')}`,description:`${members[i].plan} annual membership`,amount:plans.find(p=>p.name===members[i].plan).annualFee,status:i%7===3?'Failed':i%7===5?'Pending':'Paid',createdUtc:offset(now,-20+i/10),completedUtc:offset(now,-20+i/10),failureReason:i%7===3?'Simulated payment declined':'',provider:'Mock'}));
  const notifications=members.slice(0,16).map((m,i)=>({id:`notice-${i}`,memberId:m.id,title:i%2?'membership-approved':'registration-received',message:'Seeded fictional demonstration notification. No email or SMS sent.',channel:'Email',status:'Simulated',createdUtc:offset(now,-5+i/10)}));
  const audit=[{id:'audit-seed',actor:'System',role:'system',action:'Demo data seeded',entityId:'demo-v2',details:'50 fictional members; 64 documents; 24 attempts; 40 payments.',createdUtc:now}];
  return {version:2,seededUtc:now,users:clone(DEMO_ACCOUNTS),members,plans,documentTypes,documents,assessments,attempts,payments,notifications,audit,history:[],templates,policy:{version:'demo-1',text:'Fictional POC data only. Local browser storage. No real payments or accreditation.'},acceptances:[],support:[]};
}

export function createDemoApi({ storage=globalThis.localStorage, sessionStorage=globalThis.sessionStorage, now=()=>new Date().toISOString(), id=()=>globalThis.crypto.randomUUID() }={}) {
  let db; let session; let storageWarning='';
  try { const raw=storage.getItem(STORE_KEY);db=raw?JSON.parse(raw):null;if(db?.version!==2 || !Array.isArray(db.users)||!Array.isArray(db.members)||!Array.isArray(db.audit))db=null; } catch { storageWarning='Saved demo data could not be read. A fresh session was loaded.'; }
  db ||= seedDemo(now());
  try { const saved=sessionStorage.getItem(SESSION_KEY);session=db.users.find(u=>u.id===saved)||null; } catch { session=null; }
  function persist() { try {storage.setItem(STORE_KEY,JSON.stringify(db));}catch {storageWarning='Browser storage is unavailable or full. Changes will last only for this page session.';} }
  function actor() {if(!session)throw new Error('Sign in to continue.');return session;}
  function requireRole(...roles) {if(!roles.includes(actor().role))throw new Error('This demo role cannot perform that action.');}
  function own(memberId) {if(actor().role==='member'&&actor().memberId!==memberId)throw new Error('This record belongs to another demo member.');}
  function audit(action,entityId,details='') {db.audit.unshift({id:id(),actor:session?.name||'Visitor',role:session?.role||'public',action,entityId,details,createdUtc:now()});}
  function notify(memberId,title,message) {db.notifications.unshift({id:id(),memberId,title,message,channel:'Email',status:'Simulated',createdUtc:now()});}
  function member() {requireRole('member');return db.members.find(m=>m.id===session.memberId);}
  function memberViews() {return db.members.map(m=>{const result=db.attempts.filter(a=>a.memberId===m.id&&a.status!=='In progress').sort((a,b)=>b.submittedUtc.localeCompare(a.submittedUtc))[0];return {...m,documents:db.documents.filter(d=>d.memberId===m.id).length,assessment:result?.status||'Not started'};});}
  function refreshExpiry() {for(const m of db.members)if(['Active','Expiring'].includes(m.status)&&m.endDate){const days=(new Date(m.endDate)-new Date(now()))/86400000;const status=days<=0?'Expired':days<=30?'Expiring':'Active';if(m.status!==status){const previous=m.status;m.status=status;db.history.unshift({id:id(),memberId:m.id,previous,status,reason:'Demo annual term calculation',createdUtc:now()});audit('Membership '+status,m.id,'Automatic demo date calculation');}}}
  persist();
  return {
    get storageWarning(){return storageWarning;},
    async session(){return session?clone(session):null;},
    async login(email,password){const user=db.users.find(u=>u.email.toLowerCase()===email.trim().toLowerCase()&&u.password===password);if(!user){audit('Login failed','demo-account','No credentials recorded');persist();throw new Error('The email and password do not match a demo account.');}session=user;try{sessionStorage.setItem(SESSION_KEY,user.id);}catch{}audit('Signed in',user.id);persist();return clone(user);},
    async logout(){if(session)audit('Signed out',session.id);persist();session=null;try{sessionStorage.removeItem(SESSION_KEY);}catch{}},
    async snapshot(){actor();refreshExpiry();persist();const all=actor().role!=='member';const scoped=items=>items.filter(x=>all||x.memberId===session.memberId);const allowed=ROLE_SECTIONS[actor().role];return clone({user:session,allowedSections:allowed,members:allowed.includes('members')||allowed.includes('dashboard')?memberViews():[],profile:all?null:member(),plans:db.plans,documentTypes:db.documentTypes,documents:all?(allowed.includes('reviews')?db.documents:[]):scoped(db.documents),assessments:allowed.includes('assessments')?db.assessments.map(({questions,...a})=>({...a,questionCount:questions.length})):[],attempts:allowed.includes('assessments')?scoped(db.attempts).map(({snapshot,answers,...a})=>({...a,memberName:db.members.find(m=>m.id===a.memberId)?.name})):[],payments:allowed.includes('payments')?scoped(db.payments).map(p=>({...p,memberName:db.members.find(m=>m.id===p.memberId)?.name})):[],notifications:scoped(db.notifications),audit:allowed.includes('audit')?db.audit:[],history:scoped(db.history),stats:allowed.includes('dashboard')?{total:db.members.length,active:db.members.filter(m=>['Active','Expiring'].includes(m.status)).length,pending:db.members.filter(m=>m.status==='Pending review').length,expired:db.members.filter(m=>m.status==='Expired').length,expiring:db.members.filter(m=>m.status==='Expiring').length,documents:db.documents.filter(d=>d.status==='In review').length,failedPayments:db.payments.filter(p=>p.status==='Failed').length}:null,storageWarning});},
    async register(input){const email=String(input.email||'').trim().toLowerCase();if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!input.firstName?.trim()||!input.surname?.trim())throw new Error('Enter a fictional name and valid demo email.');if(!input.consent)throw new Error('Accept the demo privacy notice.');if(db.users.some(u=>u.email.toLowerCase()===email))throw new Error('This email already has a demo login.');const plan=input.membership==='Professional membership'?'Professional':'Annual';const memberId=`TGA-DEMO-${id().slice(0,8).toUpperCase()}`;const record={id:memberId,firstName:input.firstName.trim().slice(0,100),lastName:input.surname.trim().slice(0,100),name:`${input.firstName.trim()} ${input.surname.trim()}`.slice(0,201),email,mobile:String(input.mobile||'').slice(0,30),province:String(input.province||''),plan,status:'Pending review',startDate:null,endDate:null,address:'Fictional demonstration address',city:'Demo city',postalCode:'0000',communication:input.communication||'Email',createdUtc:now()};db.members.push(record);db.users.push({id:id(),email,password:DEMO_PASSWORD,name:record.name,role:'member',memberId,label:'Registered demo member'});db.acceptances.push({memberId,version:db.policy.version,acceptedUtc:now()});audit('Application submitted',memberId,'Demo privacy policy accepted');notify(memberId,'registration-received','Your demo application is waiting for membership administrator review.');persist();return {memberId,email,password:DEMO_PASSWORD};},
    async updateProfile(input){const m=member();if(!input.firstName?.trim()||!input.surname?.trim())throw new Error('First name and surname are required.');Object.assign(m,{firstName:input.firstName.trim().slice(0,100),lastName:input.surname.trim().slice(0,100),name:`${input.firstName.trim()} ${input.surname.trim()}`.slice(0,201),mobile:String(input.mobile||'').slice(0,30),province:String(input.province||''),address:String(input.address||'').slice(0,500),communication:input.communication||'Email'});session.name=m.name;db.users.find(u=>u.id===session.id).name=m.name;audit('Profile updated',m.id,'Contact fields updated; contents omitted from activity log');persist();},
    async changeMembership(memberId,status,reason){requireRole('admin','membership');const m=db.members.find(x=>x.id===memberId);if(!m)throw new Error('Member not found.');if(!reason?.trim())throw new Error('A review reason is required.');const transitions={'Pending review':['Active','Rejected'],Active:['Suspended','Cancelled'],Expiring:['Suspended','Cancelled'],Suspended:['Active','Cancelled'],Expired:['Cancelled'],'Payment due':['Active','Cancelled'],Rejected:['Pending review'],Cancelled:['Pending review']};if(!transitions[m.status]?.includes(status))throw new Error(`Cannot change ${m.status} to ${status}.`);const previous=m.status;m.status=status;if(status==='Active'&&!m.endDate){m.startDate=now();m.endDate=addMonths(now());}db.history.unshift({id:id(),memberId,previous,status,reason:reason.slice(0,500),actor:actor().name,createdUtc:now()});audit('Membership '+status,memberId,reason.slice(0,500));notify(memberId,status==='Active'?'membership-approved':'membership-'+status.toLowerCase(),reason.slice(0,500));persist();},
    async upload({name,type,mime,sizeBytes,expiryDate=null}){const m=member();const config=db.documentTypes.find(t=>t.id===type);const ext=name?.split('.').pop().toLowerCase();const expected={pdf:'application/pdf',jpg:'image/jpeg',jpeg:'image/jpeg',png:'image/png'}[ext];if(!config||!expected||expected!==mime||!config.mimeTypes.includes(mime))throw new Error('Choose a PDF, JPG or PNG sample.');if(sizeBytes<=0||sizeBytes>config.maxSize)throw new Error('File must be between 1 byte and 5 MB.');if(expiryDate&&!Number.isFinite(Date.parse(expiryDate)))throw new Error('Enter a valid expiry date.');const doc={id:id(),memberId:m.id,name:name.replace(/[<>\x00-\x1f]/g,'').slice(0,180),type,mime,sizeBytes,date:now(),status:'In review',expiryDate,reason:'',metadataOnly:true};db.documents.unshift(doc);audit('Document submitted',doc.id,'Demo metadata recorded');notify(m.id,'document-received','Your demo document is awaiting review.');persist();return clone(doc);},
    async reviewDocument(documentId,approved,reason){requireRole('admin','verifier');const doc=db.documents.find(d=>d.id===documentId);if(!doc)throw new Error('Document not found.');if(doc.status!=='In review')throw new Error('This document has already been reviewed.');if(!reason?.trim())throw new Error('Enter a review note.');doc.status=approved?(doc.expiryDate&&doc.expiryDate<=now()?'Expired':'Approved'):'Rejected';doc.reason=reason.slice(0,500);doc.reviewedBy=actor().name;doc.reviewedUtc=now();audit('Document '+doc.status,doc.id,doc.reason);notify(doc.memberId,'document-'+doc.status.toLowerCase(),doc.reason);persist();},
    async document(documentId){requireRole('member','admin','verifier');const doc=db.documents.find(d=>d.id===documentId);if(!doc)throw new Error('Document not found.');own(doc.memberId);audit('Document viewed',doc.id,'Demo metadata only');persist();return clone(doc);},
    async startAssessment(assessmentId){const m=member();const a=db.assessments.find(a=>a.id===assessmentId&&a.active);if(!a)throw new Error('Assessment unavailable.');let attempt=db.attempts.find(x=>x.memberId===m.id&&x.assessmentId===a.id&&x.status==='In progress');if(attempt&&attempt.timeLimitMinutes&&new Date(now())>new Date(new Date(attempt.startedUtc).getTime()+attempt.timeLimitMinutes*60000)){attempt.status='Abandoned';attempt.submittedUtc=now();audit('Assessment time expired',attempt.id);persist();attempt=null;}if(!attempt){if(db.attempts.filter(x=>x.memberId===m.id&&x.assessmentId===a.id).length>=a.maxAttempts)throw new Error(`Maximum of ${a.maxAttempts} attempts reached. Ask an assessor to adjust the demo limit.`);attempt={id:id(),memberId:m.id,assessmentId:a.id,title:a.title,startedUtc:now(),submittedUtc:null,status:'In progress',snapshot:clone(a.questions),passMark:a.passMark,timeLimitMinutes:a.timeLimitMinutes};db.attempts.unshift(attempt);audit('Assessment started',attempt.id);persist();}return clone({...attempt,snapshot:undefined,questions:attempt.snapshot.map(({correct,...q})=>q)});},
    async submitAssessment(attemptId,answers){const m=member();const a=db.attempts.find(a=>a.id===attemptId&&a.memberId===m.id);if(!a||a.status!=='In progress')throw new Error('This attempt is no longer open.');if(a.timeLimitMinutes&&new Date(now())>new Date(new Date(a.startedUtc).getTime()+a.timeLimitMinutes*60000)){a.status='Abandoned';a.submittedUtc=now();audit('Assessment time expired',a.id);persist();throw new Error('The assessment time limit has expired.');}if(a.snapshot.some(q=>!Number.isInteger(answers[q.id])||answers[q.id]<0||answers[q.id]>=q.options.length))throw new Error('Answer every question.');const correct=a.snapshot.filter(q=>answers[q.id]===q.correct).length;a.percentage=Math.round(correct/a.snapshot.length*100);a.passed=a.percentage>=a.passMark;a.status=a.passed?'Passed':'Failed';a.submittedUtc=now();a.answers=clone(answers);audit('Assessment '+a.status,a.id,`${a.percentage}%; demo/non-accredited`);notify(m.id,'assessment-result',`${a.title}: ${a.percentage}% — ${a.status}. Demo only, non-accredited.`);persist();const {snapshot,...result}=a;return clone(result);},
    async configureAssessment(assessmentId,{passMark,maxAttempts,timeLimitMinutes}){requireRole('admin','assessor');const a=db.assessments.find(a=>a.id===assessmentId);if(!a)throw new Error('Assessment not found.');if(!Number.isInteger(passMark)||passMark<1||passMark>100||!Number.isInteger(maxAttempts)||maxAttempts<1||maxAttempts>20||timeLimitMinutes!==null&&(!Number.isInteger(timeLimitMinutes)||timeLimitMinutes<1||timeLimitMinutes>180))throw new Error('Use pass mark 1–100, attempts 1–20 and time 1–180 minutes or blank.');Object.assign(a,{passMark,maxAttempts,timeLimitMinutes});audit('Assessment rules updated',a.id,`Pass ${passMark}%; max attempts ${maxAttempts}; time ${timeLimitMinutes??'unlimited'}`);persist();},
    async checkout(){const m=member();if(['Suspended','Cancelled','Rejected'].includes(m.status))throw new Error('This membership cannot make a renewal payment.');let p=db.payments.find(p=>p.memberId===m.id&&p.status==='Pending');if(!p){const plan=db.plans.find(p=>p.name===m.plan);p={id:id(),memberId:m.id,reference:`TGA-MOCK-${id().slice(0,8).toUpperCase()}`,description:`${m.plan} annual membership`,amount:plan.annualFee+(m.startDate?0:plan.joiningFee),status:'Pending',createdUtc:now(),provider:'Mock'};db.payments.unshift(p);audit('Mock checkout created',p.id,'No real money is collected');persist();}return clone(p);},
    async completePayment(paymentId,outcome){const m=member();const p=db.payments.find(p=>p.id===paymentId&&p.memberId===m.id);if(!p)throw new Error('Payment not found.');if(p.status!=='Pending')return clone(p);if(!['Paid','Failed','Cancelled'].includes(outcome))throw new Error('Choose a valid mock outcome.');if(['Suspended','Cancelled','Rejected'].includes(m.status))throw new Error('Membership no longer accepts this payment.');p.status=outcome;p.completedUtc=now();p.failureReason=outcome==='Failed'?'Simulated payment declined — no money moved.':'';if(outcome==='Paid'&&m.status!=='Pending review'){const previous=m.status;m.startDate||=now();m.endDate=addMonths(m.endDate&&m.endDate>now()?m.endDate:now());m.status='Active';db.history.unshift({id:id(),memberId:m.id,previous,status:'Active',reason:'Simulated annual payment',createdUtc:now()});}audit('Mock payment '+outcome,p.id,`${p.amount.toFixed(2)} ZAR; no money moved`);notify(m.id,outcome==='Paid'?'payment-successful':'payment-'+outcome.toLowerCase(),`${p.reference}: ${outcome}. No real transaction.`);persist();return clone(p);},
    async refund(paymentId,reason){requireRole('admin','finance');const p=db.payments.find(p=>p.id===paymentId);if(!p||p.status!=='Paid')throw new Error('Only a paid demo transaction can be refunded once.');if(!reason?.trim())throw new Error('A refund reason is required.');p.status='Refunded';p.refundedUtc=now();p.refundReason=reason.slice(0,500);audit('Mock refund recorded',p.id,p.refundReason);notify(p.memberId,'payment-refunded',`Demo refund recorded for ${p.reference}. No money moved. Membership unchanged pending policy review.`);persist();},
    async recover(email){const u=db.users.find(u=>u.email.toLowerCase()===String(email).trim().toLowerCase());audit('Demo password reminder requested','demo-account','Public POC credential reminder');persist();return u?{email:u.email,password:u.password}:null;},
    async support(message){actor();if(!message?.trim())throw new Error('Enter a short description.');const ticket={id:`TGA-SUPPORT-${id().slice(0,8).toUpperCase()}`,memberId:session.memberId||null,message:message.slice(0,1000),status:'Open',createdUtc:now()};db.support.unshift(ticket);audit('Demo support request created',ticket.id);notify(ticket.memberId,'support-request',`${ticket.id}: saved locally; no message sent.`);persist();return clone(ticket);},
    async exportMembers(){requireRole('admin','membership');audit('Member CSV exported','member-register',`${db.members.length} fictional records`);persist();return clone(memberViews());},
    async reset(){requireRole('admin');db=seedDemo(now());session=db.users.find(u=>u.id==='user-admin');audit('Demo reset','demo-v2','Restored default fixtures');persist();return true;}
  };
}
