// ASP.NET Core adapter. Access tokens stay in memory; refresh cookies are HttpOnly.
import {ROLE_SECTIONS,DEMO_PASSWORD} from './demo-api.js';
export function createHttpApi(baseUrl) {
 let token=null,refreshing=null,user=null,cache=null;const attempts=new Map();const roleNames={SystemAdministrator:'admin',MembershipAdministrator:'membership',DocumentVerifier:'verifier',FinanceUser:'finance',Assessor:'assessor',SupportAgent:'support',Member:'member'};
 async function refresh(){if(!refreshing)refreshing=fetch(baseUrl+'/api/auth/refresh',{method:'POST',credentials:'include'}).then(async r=>{if(!r.ok){token=null;user=null;throw new Error('Your session expired. Please sign in again.');}const data=await r.json();token=data.accessToken;return data;}).finally(()=>refreshing=null);return refreshing;}
 async function request(path,{method='GET',body,blob=false,retry=true}={}){const multipart=body instanceof FormData;let response;try{response=await fetch(baseUrl+path,{method,credentials:'include',headers:{...(token?{Authorization:'Bearer '+token}:{}),...(!multipart&&body?{'Content-Type':'application/json'}:{})},body:body?(multipart?body:JSON.stringify(body)):undefined,signal:AbortSignal.timeout(60000)});}catch{throw new Error('The sandbox API is unavailable or starting up. Try again in a moment.');}if(response.status===401&&retry&&token){await refresh();return request(path,{method,body,blob,retry:false});}if(!response.ok){const error=await response.json().catch(()=>({}));throw new Error(error.errors?Object.values(error.errors).flat().join(' '):error.title||`Request failed (${response.status}).`);}if(response.status===204)return null;return blob?response.blob():response.json();}
 const status=s=>s==='Pending'?'Pending review':s==='PendingReview'?'In review':s;
 function mapUser(u,profile){const role=u.roles.map(r=>roleNames[r]).find(r=>r&&r!=='member')||'member';return {id:u.id,email:u.email,role,name:profile?profile.firstName+' '+profile.lastName:'TGA '+role,label:role==='member'?'Member':role+' administrator',memberId:profile?.membershipNumber};}
 async function identity(u){const role=u.roles.map(r=>roleNames[r]).find(r=>r&&r!=='member')||'member';const profile=role==='member'?await request('/api/me/profile'):null;user=mapUser(u,profile);return user;}
 const mapDoc=d=>({id:d.id,memberId:d.memberId,memberName:d.memberName,name:d.name,type:d.type,date:d.date,status:status(d.status),sizeBytes:d.size,reason:d.rejectionReason,expiryDate:d.expiryDate,metadataOnly:false});
 const mapPayment=p=>({...p,createdUtc:p.date,description:p.paymentType,provider:'Mock'});
 async function page(path){const result=await request(path+(path.includes('?')?'&':'?')+'pageSize=100');return result.items||result;}
 const api={
  storageWarning:'',
  async session(){try{const data=await refresh();return await identity(data.user);}catch{return null;}},
  async login(email,password){const data=await request('/api/auth/login',{method:'POST',body:{email,password},retry:false});token=data.accessToken;return identity(data.user);},
  async logout(){try{await request('/api/auth/logout',{method:'POST'});}finally{token=null;user=null;cache=null;}},
  async snapshot(){if(!user)throw new Error('Sign in to continue.');const member=user.role==='member';const allowed=ROLE_SECTIONS[user.role];const has=section=>allowed.includes(section);const [plans,types,profile,membership,members,documents,assessments,results,payments,notifications,audit,stats,history]=await Promise.all([
    request('/api/membership-plans'),request('/api/documents/types'),member?request('/api/me/profile'):null,member?request('/api/me/membership'):null,
    has('members')?page('/api/admin/members'):[],member?request('/api/me/documents'):has('reviews')?page('/api/admin/documents/pending'):[],has('assessments')?request('/api/assessments'):[],has('assessments')?(member?request('/api/me/assessments'):page('/api/admin/assessment-results')):[],has('payments')?(member?request('/api/me/payments'):page('/api/admin/payments')):[],request(user.role==='admin'?'/api/admin/notifications':'/api/notifications'),has('audit')?page('/api/admin/audit'):[],has('dashboard')?request('/api/admin/dashboard'):null,member?request('/api/me/membership-history'):['admin','membership'].includes(user.role)?request('/api/admin/membership-history'):[]]);
    if(profile)user.name=profile.firstName+' '+profile.lastName;
    cache={user,allowedSections:allowed,dataMode:'api',members:members.map(m=>({...m,status:status(m.status)})),profile:profile?{...profile,id:profile.membershipNumber,name:profile.firstName+' '+profile.lastName,mobile:profile.mobileNumber,communication:'Email',plan:membership.plan,status:status(membership.status),startDate:membership.startDate,endDate:membership.endDate}:null,plans:plans.map(p=>({...p,annualFee:p.annualFee})),documentTypes:types.map(t=>({...t,maxSize:t.maxSizeBytes})),documents:documents.map(mapDoc),assessments:assessments.map(a=>({...a,passMark:a.passPercentage,active:true})),attempts:results.map(a=>({...a,title:a.assessmentTitle,assessmentId:assessments.find(x=>x.title===a.assessmentTitle)?.id})),payments:payments.map(mapPayment),notifications:notifications.map(n=>({...n,title:n.templateKey,message:'Sandbox notification recorded. No email or SMS sent.'})),audit:audit.map(a=>({...a,createdUtc:a.timestampUtc,actor:a.actorUserId||'System',role:'',details:a.entityType})),stats:stats?{total:stats.totalMembers,active:stats.activeMembers,pending:stats.pendingApplications,expired:stats.expiredMemberships,expiring:stats.expiringMemberships,documents:stats.pendingDocuments,failedPayments:stats.failedPayments}:null,history:history.map(h=>({...h,previous:status(h.previous),status:status(h.status)}))};return cache;},
  async register(input){const plans=await request('/api/membership-plans');const policies=await request('/api/policies');const plan=plans.find(p=>p.name===(input.membership==='Professional membership'?'Professional':'Annual'));if(!input.consent)throw new Error('Accept the sandbox policy.');const r=await request('/api/auth/register',{method:'POST',body:{email:input.email,password:DEMO_PASSWORD,firstName:input.firstName,lastName:input.surname,planId:plan.id,policyIds:policies.map(p=>p.id)}});return {memberId:r.membershipNumber,email:input.email,password:DEMO_PASSWORD};},
  async updateProfile(input){return request('/api/me/profile',{method:'PATCH',body:{firstName:input.firstName,lastName:input.surname,mobileNumber:input.mobile||'',province:input.province||'',address:input.address||''}});},
  async changeMembership(id,next,reason){const m=cache.members.find(m=>m.id===id);if(!m)throw new Error('Reload the member register.');return request('/api/admin/memberships/'+m.membershipId,{method:'PATCH',body:{status:next==='Pending review'?'Pending':next,reason}});},
  async upload({file,name,type,mime,sizeBytes}){if(!file)throw new Error('Choose a sample file.');const kind=cache.documentTypes.find(t=>t.name===type);const form=new FormData();form.append('file',file);form.append('documentTypeId',kind.id);return request('/api/documents',{method:'POST',body:form});},
  async document(id){return mapDoc(await request('/api/documents/'+id));},
  async download(id){return request('/api/documents/'+id+'/download',{blob:true});},
  async reviewDocument(id,approved,reason){return request('/api/admin/documents/'+id+'/'+(approved?'approve':'reject'),{method:'POST',body:{reason}});},
  async startAssessment(id){const a=await request('/api/assessments/'+id+'/attempts',{method:'POST'});attempts.set(a.id,a);const config=cache.assessments.find(x=>x.id===id);return {...a,title:config.title,passMark:config.passMark,questions:a.questions.map(q=>({...q,options:q.options.map(o=>o.text)}))};},
  async submitAssessment(id,answers){const a=attempts.get(id);if(!a)throw new Error('Reopen this assessment to resume it.');const selected=Object.fromEntries(a.questions.map(q=>[q.id,[q.options[answers[q.id]]?.id]]));await request('/api/assessment-attempts/'+id+'/answers',{method:'PUT',body:{answers:selected}});return request('/api/assessment-attempts/'+id+'/submit',{method:'POST'});},
  async configureAssessment(id,rules){const a=cache.assessments.find(a=>a.id===id);return request('/api/admin/assessments/'+id,{method:'PATCH',body:{title:a.title,description:a.description,passPercentage:rules.passMark,maxAttempts:rules.maxAttempts,timeLimitMinutes:rules.timeLimitMinutes,isActive:true}});},
  async checkout(){const r=await request('/api/payments/checkout',{method:'POST',body:{paymentType:'Renewal'}});const payments=await request('/api/me/payments');return mapPayment(payments.find(p=>p.id===r.paymentId));},
  async completePayment(id,outcome){await request('/api/payments/'+id+(outcome==='Cancelled'?'/cancel':'/mock-complete'),{method:'POST',body:outcome==='Cancelled'?undefined:{success:outcome==='Paid'}});return mapPayment((await request('/api/me/payments')).find(p=>p.id===id));},
  async refund(id,reason){return request('/api/admin/payments/'+id+'/refund',{method:'POST',body:{reason}});},
  async recover(email){await request('/api/auth/forgot-password',{method:'POST',body:{email}});return null;},
  async support(message){return request('/api/support',{method:'POST',body:{message}});},
  async exportMembers(){const rows=await page('/api/admin/members');await request('/api/admin/reports/members.csv',{blob:true});return rows;},
  async reset(){await request('/api/demo/reset',{method:'POST'});token=null;user=null;throw new Error('Demo database restored. Please sign in again.');}
 };return api;
}
