using System.ComponentModel.DataAnnotations;
using System.Text;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Tga.Application;
using Tga.Domain;
using Tga.Infrastructure.Persistence;
using Tga.Infrastructure.Services;
namespace Tga.Api.Controllers;
[ApiController,Authorize(Policy=Policies.Staff),Route("api/admin")]
public class AdminController(TgaDbContext db,IMembershipService service,IAuditService audit,ICurrentUserService user,INotificationService notifications,TimeProvider clock,IConfiguration config) : ControllerBase {
 int Size(int pageSize)=>Math.Clamp(pageSize,1,config.GetValue("Pagination:MaxPageSize",100));
 [Authorize(Policy=Policies.Support),HttpGet("members")]public async Task<IActionResult> Members(CancellationToken ct,int page=1,int pageSize=25,string? search=null,string? status=null,string sort="name"){
  var q=db.Memberships.AsNoTracking();if(!string.IsNullOrWhiteSpace(search)){var term=search.Trim();q=q.Where(x=>x.Member.FirstName.Contains(term)||x.Member.LastName.Contains(term)||x.Member.Email.Contains(term)||x.Member.MembershipNumber.Contains(term));}if(Enum.TryParse<MembershipStatus>(status,true,out var parsed))q=q.Where(x=>x.Status==parsed);var total=await q.CountAsync(ct);pageSize=Size(pageSize);page=Math.Max(1,page);q=sort=="expiry"?q.OrderBy(x=>x.EndDate).ThenBy(x=>x.Id):q.OrderBy(x=>x.Member.FirstName).ThenBy(x=>x.Id);
  var rows=await q.Skip((page-1)*pageSize).Take(pageSize).Select(x=>new MemberDto(x.MemberId,x.Id,x.Member.MembershipNumber,x.Member.FirstName+" "+x.Member.LastName,x.Member.Email,x.Member.Province,x.Plan.Name,x.Status.ToString(),x.EndDate,db.Documents.Count(d=>d.MemberId==x.MemberId),db.Attempts.Where(a=>a.MemberId==x.MemberId&&a.SubmittedUtc!=null).OrderByDescending(a=>a.SubmittedUtc).Select(a=>a.Status.ToString()).FirstOrDefault()??"Not started")).ToListAsync(ct);return Ok(new PageResult<MemberDto>(rows,total,page,pageSize));
 }
 [Authorize(Policy=Policies.Support),HttpGet("members/{id:guid}")]public async Task<IActionResult> Member(Guid id,CancellationToken ct)=>Ok(await db.Members.AsNoTracking().Where(x=>x.Id==id).Profiles().SingleOrDefaultAsync(ct)??throw new RuleException("Member not found.",404));
 [Authorize(Policy=Policies.Members),HttpPatch("memberships/{id:guid}")]public async Task<IActionResult> Status(Guid id,StatusRequest r,CancellationToken ct){await service.ChangeAsync(id,r.Status,r.Reason,ct);return NoContent();}
 [Authorize(Policy=Policies.Members),HttpPost("memberships/{id:guid}/approve")]public async Task<IActionResult> Approve(Guid id,ReviewRequest r,CancellationToken ct){await service.ChangeAsync(id,MembershipStatus.Active,r.Reason,ct);return NoContent();}
 [Authorize(Policy=Policies.Members),HttpPost("memberships/{id:guid}/reject")]public async Task<IActionResult> Reject(Guid id,ReviewRequest r,CancellationToken ct){await service.ChangeAsync(id,MembershipStatus.Rejected,r.Reason,ct);return NoContent();}
 [Authorize(Policy=Policies.Members),HttpPost("memberships/{id:guid}/suspend")]public async Task<IActionResult> Suspend(Guid id,ReviewRequest r,CancellationToken ct){await service.ChangeAsync(id,MembershipStatus.Suspended,r.Reason,ct);return NoContent();}
 [Authorize(Policy=Policies.Members),HttpGet("membership-history")]public async Task<IActionResult> History(CancellationToken ct,int page=1,int pageSize=100){var q=db.Set<MembershipStatusHistory>().AsNoTracking();return Ok(await q.OrderByDescending(x=>x.ChangedUtc).Skip((Math.Max(1,page)-1)*Size(pageSize)).Take(Size(pageSize)).Select(x=>new{x.Id,MemberId=db.Memberships.Where(m=>m.Id==x.MembershipId).Select(m=>m.Member.MembershipNumber).First(),Previous=x.PreviousStatus,Status=x.NewStatus,x.Reason,CreatedUtc=x.ChangedUtc}).ToListAsync(ct));}
 [Authorize(Policy=Policies.Members),HttpGet("dashboard")]public async Task<IActionResult> Dashboard(CancellationToken ct){await service.ExpireAsync(ct);var now=clock.GetUtcNow().UtcDateTime;var attempts=await db.Attempts.CountAsync(x=>x.SubmittedUtc!=null,ct);var passed=await db.Attempts.CountAsync(x=>x.Passed,ct);var income=await db.Payments.Where(x=>x.Status==PaymentStatus.Paid).SumAsync(x=>(decimal?)x.Amount,ct)??0;var refunds=await db.Set<Refund>().Where(x=>x.Status=="Completed").SumAsync(x=>(decimal?)x.Amount,ct)??0;return Ok(new DashboardDto(await db.Members.CountAsync(ct),await db.Memberships.CountAsync(x=>x.Status==MembershipStatus.Active||x.Status==MembershipStatus.Expiring,ct),await db.Applications.CountAsync(x=>x.Status=="Pending",ct),await db.Memberships.CountAsync(x=>(x.Status==MembershipStatus.Active||x.Status==MembershipStatus.Expiring)&&x.EndDate>now&&x.EndDate<=now.AddDays(30),ct),await db.Memberships.CountAsync(x=>x.Status==MembershipStatus.Expired,ct),await db.Documents.CountAsync(x=>x.Status==DocumentStatus.PendingReview,ct),await db.Documents.CountAsync(x=>x.Status==DocumentStatus.Rejected,ct),attempts,attempts==0?0:Math.Round(100m*passed/attempts,2),await db.Payments.CountAsync(x=>x.Status==PaymentStatus.Paid,ct),await db.Payments.CountAsync(x=>x.Status==PaymentStatus.Failed,ct),income,refunds));}
 [Authorize(Policy=Policies.Documents),HttpGet("documents/pending")]public async Task<IActionResult> Documents(CancellationToken ct,int page=1,int pageSize=25,string? status=null){var q=db.Documents.AsNoTracking();if(Enum.TryParse<DocumentStatus>(status,out var parsed))q=q.Where(x=>x.Status==parsed);var total=await q.CountAsync(ct);pageSize=Size(pageSize);return Ok(new PageResult<DocumentDto>(await q.OrderByDescending(x=>x.UploadedUtc).Skip((Math.Max(1,page)-1)*pageSize).Take(pageSize).DocumentDtos().ToListAsync(ct),total,Math.Max(1,page),pageSize));}
 [Authorize(Policy=Policies.Assessments),HttpGet("assessment-results")]public async Task<IActionResult> Attempts(CancellationToken ct,int page=1,int pageSize=25){var q=db.Attempts.AsNoTracking();pageSize=Size(pageSize);return Ok(new PageResult<ResultDto>(await q.OrderByDescending(x=>x.StartedUtc).Skip((Math.Max(1,page)-1)*pageSize).Take(pageSize).ResultDtos().ToListAsync(ct),await q.CountAsync(ct),Math.Max(1,page),pageSize));}
 [Authorize(Policy=Policies.Payments),HttpGet("payments")]public async Task<IActionResult> Payments(CancellationToken ct,int page=1,int pageSize=25,PaymentStatus? status=null,DateTime? from=null,DateTime? to=null){var q=db.Payments.AsNoTracking();if(status.HasValue)q=q.Where(x=>x.Status==status);if(from.HasValue)q=q.Where(x=>x.CreatedUtc>=from);if(to.HasValue)q=q.Where(x=>x.CreatedUtc<=to);pageSize=Size(pageSize);return Ok(new PageResult<PaymentDto>(await q.OrderByDescending(x=>x.CreatedUtc).Skip((Math.Max(1,page)-1)*pageSize).Take(pageSize).PaymentDtos().ToListAsync(ct),await q.CountAsync(ct),Math.Max(1,page),pageSize));}
 [Authorize(Policy=Policies.Audit),HttpGet("audit")]public async Task<IActionResult> Audit(CancellationToken ct,int page=1,int pageSize=25){var q=db.Set<AuditEvent>().AsNoTracking();pageSize=Size(pageSize);return Ok(new PageResult<AuditDto>(await q.OrderByDescending(x=>x.TimestampUtc).Skip((Math.Max(1,page)-1)*pageSize).Take(pageSize).Select(x=>new AuditDto(x.Id,x.TimestampUtc,x.ActorUserId,x.Action,x.EntityType,x.EntityId,x.CorrelationId)).ToListAsync(ct),await q.CountAsync(ct),Math.Max(1,page),pageSize));}
 [Authorize(Policy=Policies.System),HttpGet("notifications")]public async Task<IActionResult> NotificationLogs(CancellationToken ct,int page=1,int pageSize=100){var q=db.Set<NotificationLog>().AsNoTracking();return Ok(await q.OrderByDescending(x=>x.CreatedUtc).Skip((Math.Max(1,page)-1)*Size(pageSize)).Take(Size(pageSize)).Select(x=>new NotificationDto(x.Id,x.Channel,x.TemplateKey,x.Status,x.Provider,x.CreatedUtc)).ToListAsync(ct));}
 [Authorize(Policy=Policies.Payments),HttpPost("payments/{id:guid}/refund")]public async Task<IActionResult> Refund(Guid id,ReviewRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var p=await db.Payments.Include(x=>x.Member).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new RuleException("Payment not found.",404);if(p.Provider!="Mock"||p.Status!=PaymentStatus.Paid)throw new RuleException("Only a paid mock transaction can be refunded.",409);p.Status=PaymentStatus.Refunded;db.Add(new Refund{PaymentTransactionId=id,Amount=p.Amount,Reason=r.Reason,RequestedBy=user.UserId,ApprovedBy=user.UserId,Status="Completed",CompletedUtc=clock.GetUtcNow().UtcDateTime,ProviderReference="mock-refund-"+Guid.NewGuid().ToString("N")});audit.Record("MockRefundCompleted",nameof(PaymentTransaction),id);notifications.Enqueue(p.Member.UserId,"payment-refunded");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);await notifications.DispatchAsync(ct);return NoContent();}
 [Authorize(Policy=Policies.Members),HttpGet("reports/members.csv")]public async Task<IActionResult> Export(CancellationToken ct){var rows=await db.Memberships.AsNoTracking().OrderBy(x=>x.Member.MembershipNumber).Take(10000).Select(x=>new{x.Member.MembershipNumber,x.Member.FirstName,x.Member.LastName,x.Status,x.EndDate}).ToListAsync(ct);static string Csv(string? x)=>"\""+((x??"").StartsWith('=')||(x??"").StartsWith('+')||(x??"").StartsWith('-')||(x??"").StartsWith('@')?"'":"")+(x??"").Replace("\"","\"\"")+"\"";var text="Member number,First name,Last name,Status,Expiry\r\n"+string.Join("\r\n",rows.Select(x=>string.Join(',',new[]{x.MembershipNumber,x.FirstName,x.LastName,x.Status.ToString(),x.EndDate?.ToString("O")}.Select(Csv))));audit.Record("MemberRegisterExported","Report",Guid.Empty);await db.SaveChangesAsync(ct);return File(Encoding.UTF8.GetBytes(text),"text/csv","tga-demo-members.csv");}
}
