using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Tga.Api.Security;
using Tga.Application;
using Tga.Domain;
using Tga.Infrastructure.Persistence;
namespace Tga.Api.Controllers;
[ApiController,Route("api/auth"),EnableRateLimiting("auth")]
public class AuthController(TgaDbContext db,UserManager<AppUser> users,SignInManager<AppUser> signIn,AuthService auth,ICurrentUserService current,IMembershipNumberGenerator numbers,IAuditService audit,INotificationService notifications,IConfiguration config,TimeProvider clock) : ControllerBase {
 [HttpPost("register")] public async Task<IActionResult> Register(RegisterRequest r,CancellationToken ct) {
  var plan=await db.Plans.SingleOrDefaultAsync(x=>x.Id==r.PlanId&&x.IsActive,ct)??throw new RuleException("Choose an active membership plan.");var policies=await db.Set<PolicyDocument>().Where(x=>x.IsActive).Select(x=>x.Id).ToArrayAsync(ct);if(r.PolicyIds==null||policies.Except(r.PolicyIds).Any())throw new RuleException("Accept current sandbox policies.");
  await using var tx=await db.Database.BeginTransactionAsync(ct);var user=new AppUser{UserName=r.Email,Email=r.Email};var result=await users.CreateAsync(user,r.Password);if(!result.Succeeded)return ValidationProblem(new ValidationProblemDetails(new Dictionary<string,string[]>{{"account",result.Errors.Select(x=>x.Description).ToArray()}}));await users.AddToRoleAsync(user,Roles.Member);
  var member=new MemberProfile{UserId=user.Id,Email=r.Email,FirstName=r.FirstName,LastName=r.LastName,MembershipNumber=numbers.Generate()};db.Add(member);db.Add(new Membership{MemberId=member.Id,MembershipPlanId=plan.Id});db.Add(new MembershipApplication{MemberId=member.Id,MembershipPlanId=plan.Id,SubmittedUtc=clock.GetUtcNow().UtcDateTime});foreach(var id in policies)db.Add(new UserPolicyAcceptance{UserId=user.Id,PolicyDocumentId=id,AcceptedUtc=clock.GetUtcNow().UtcDateTime});notifications.Enqueue(user.Id,"registration-received");notifications.Enqueue(user.Id,"email-verification");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);await notifications.DispatchAsync(ct);return StatusCode(201,new{memberId=member.Id,member.MembershipNumber,message="Sandbox registration saved. Email delivery is simulated."});
 }
 [HttpPost("login")] public async Task<IActionResult> Login(LoginRequest r,CancellationToken ct) {var user=await users.FindByEmailAsync(r.Email);var valid=user!=null&&user.IsActive&&(await signIn.CheckPasswordSignInAsync(user,r.Password,true)).Succeeded;if(!valid){audit.Record("LoginFailed","Account",Guid.Empty);await db.SaveChangesAsync(ct);return Problem(statusCode:401,title:"Invalid credentials or account locked.");}return Ok(await auth.IssueAsync(user!,Response,ct:ct));}
 [HttpPost("refresh")] public async Task<IActionResult> Refresh(CancellationToken ct) {auth.ValidateOrigin(Request);var token=Request.Cookies["tga_refresh"];if(token==null)return Unauthorized();await using var tx=await db.Database.BeginTransactionAsync(ct);var hash=AuthService.Hash(token);var session=await db.Set<RefreshSession>().SingleOrDefaultAsync(x=>x.TokenHash==hash,ct);var now=clock.GetUtcNow().UtcDateTime;if(session==null||session.ExpiresUtc<=now)return Unauthorized();if(session.RevokedUtc!=null){await db.Set<RefreshSession>().Where(x=>x.FamilyId==session.FamilyId&&x.RevokedUtc==null).ExecuteUpdateAsync(x=>x.SetProperty(s=>s.RevokedUtc,now),ct);await tx.CommitAsync(ct);return Unauthorized();}var user=await users.FindByIdAsync(session.UserId);if(user==null||!user.IsActive)return Unauthorized();session.RevokedUtc=now;await db.SaveChangesAsync(ct);var result=await auth.IssueAsync(user,Response,session.FamilyId,ct);await tx.CommitAsync(ct);return Ok(result);}
 [HttpPost("logout")] public async Task<IActionResult> Logout(CancellationToken ct) {auth.ValidateOrigin(Request);var token=Request.Cookies["tga_refresh"];if(token!=null){var hash=AuthService.Hash(token);var s=await db.Set<RefreshSession>().SingleOrDefaultAsync(x=>x.TokenHash==hash,ct);if(s!=null)await db.Set<RefreshSession>().Where(x=>x.FamilyId==s.FamilyId).ExecuteUpdateAsync(x=>x.SetProperty(s=>s.RevokedUtc,clock.GetUtcNow().UtcDateTime),ct);}Response.Cookies.Delete("tga_refresh",auth.Cookie());return NoContent();}
 [Authorize,HttpGet("me")] public async Task<IActionResult> Me(){var u=await users.FindByIdAsync(current.UserId);return Ok(new{id=u!.Id,email=u.Email,roles=await users.GetRolesAsync(u)});}
 [HttpPost("forgot-password")] public async Task<IActionResult> Forgot(EmailRequest r,CancellationToken ct){var u=await users.FindByEmailAsync(r.Email);if(u!=null){notifications.Enqueue(u.Id,"password-reset");await db.SaveChangesAsync(ct);await notifications.DispatchAsync(ct);}return Ok(new{message="If this account exists, a request is recorded. Sandbox email is simulated."});}
 [HttpPost("reset-password")] public async Task<IActionResult> Reset(ResetPasswordRequest r,CancellationToken ct){var u=await users.FindByEmailAsync(r.Email);if(u==null||!(await users.ResetPasswordAsync(u,r.Token,r.Password)).Succeeded)return Problem(statusCode:400,title:"Invalid or expired reset request.");await db.Set<RefreshSession>().Where(x=>x.UserId==u.Id).ExecuteUpdateAsync(x=>x.SetProperty(s=>s.RevokedUtc,clock.GetUtcNow().UtcDateTime),ct);return NoContent();}
 [HttpPost("verify-email")] public async Task<IActionResult> Verify(VerifyEmailRequest r){var u=await users.FindByIdAsync(r.UserId);return u!=null&&(await users.ConfirmEmailAsync(u,r.Token)).Succeeded?NoContent():Problem(statusCode:400,title:"Invalid verification request.");}
 [Authorize(Policy=Policies.System),HttpPost("demo-account-token/{userId}")] public async Task<IActionResult> DemoToken(string userId,[FromQuery]string purpose="reset"){if((config["TGA_DATA_MODE"]??"Demo")!="Demo")return NotFound();var u=await users.FindByIdAsync(userId)??throw new RuleException("Account not found.",404);return Ok(new{token=purpose=="verify"?await users.GenerateEmailConfirmationTokenAsync(u):await users.GeneratePasswordResetTokenAsync(u),demoOnly=true});}
}
