using System.ComponentModel.DataAnnotations;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.RateLimiting;
using Microsoft.EntityFrameworkCore;
using Tga.Application;
using Tga.Domain;
using Tga.Infrastructure.Persistence;
using Tga.Infrastructure.Services;
namespace Tga.Api.Controllers;
public class DocumentUpload { [Required] public IFormFile File {get;set;}=null!;public Guid DocumentTypeId{get;set;}public DateTime? ExpiryDate{get;set;} }
[ApiController,Authorize,Route("api/documents")]
public class DocumentsController(TgaDbContext db,ICurrentUserService user,IAuthorizationService authorization,IDocumentStorageService storage,IFileSecurityScanner scanner,IAuditService audit,INotificationService notifications,TimeProvider clock) : ControllerBase {
 [HttpGet("types")]public async Task<IActionResult> Types(CancellationToken ct)=>Ok(await db.DocumentTypes.AsNoTracking().Where(x=>x.IsActive).Select(x=>new{x.Id,x.Name,x.IsRequired,x.RequiresExpiryDate,x.MaxSizeBytes,x.AllowedMimeTypes}).ToListAsync(ct));
 [HttpPost,EnableRateLimiting("upload"),RequestSizeLimit(6*1024*1024)]public async Task<IActionResult> Upload([FromForm]DocumentUpload r,CancellationToken ct){var m=await db.OwnMember(user,ct);var type=await db.DocumentTypes.SingleOrDefaultAsync(x=>x.Id==r.DocumentTypeId&&x.IsActive,ct)??throw new RuleException("Invalid document type.");if(type.RequiresExpiryDate&&!r.ExpiryDate.HasValue)throw new RuleException("Expiry date required.");await using var input=r.File.OpenReadStream();var header=new byte[8];await input.ReadAtLeastAsync(header,8,false,ct);DocumentRules.Validate(r.File.FileName,r.File.ContentType,r.File.Length,type,header);input.Position=0;if(!await scanner.IsCleanAsync(input,ct))throw new RuleException("File rejected by security scanner.");input.Position=0;var stored=await storage.UploadAsync(input,ct);try{var d=new MemberDocument{MemberId=m.Id,DocumentTypeId=type.Id,OriginalFileName=Path.GetFileName(r.File.FileName.Replace('\\','/')).Replace("\r","").Replace("\n","")[..Math.Min(Path.GetFileName(r.File.FileName.Replace('\\','/')).Replace("\r","").Replace("\n","").Length,180)],MimeType=r.File.ContentType,SizeBytes=stored.Size,StorageKey=stored.Key,Checksum=stored.Checksum,UploadedUtc=clock.GetUtcNow().UtcDateTime,ExpiryDate=r.ExpiryDate};db.Add(d);audit.Record("DocumentUploaded",nameof(MemberDocument),d.Id);notifications.Enqueue(m.UserId,"document-received");await db.SaveChangesAsync(ct);await notifications.DispatchAsync(ct);return Created("/api/documents/"+d.Id,new{id=d.Id});}catch{await storage.DeleteAsync(stored.Key,ct);throw;}}
 async Task<MemberDocument> Access(Guid id,CancellationToken ct){var d=await db.Documents.Include(x=>x.Member).Include(x=>x.Type).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new RuleException("Document not found.",404);if(d.Member.UserId!=user.UserId&&!(await authorization.AuthorizeAsync(User,Policies.Documents)).Succeeded)throw new RuleException("Document not found.",404);return d;}
 [HttpGet("{id:guid}")]public async Task<IActionResult> Get(Guid id,CancellationToken ct){var d=await Access(id,ct);audit.Record("DocumentViewed",nameof(MemberDocument),id);await db.SaveChangesAsync(ct);return Ok(new DocumentDto(d.Id,d.MemberId,d.Member.FirstName+" "+d.Member.LastName,d.OriginalFileName,d.Type.Name,d.UploadedUtc,d.Status,d.SizeBytes,d.RejectionReason,d.ExpiryDate));}
 [HttpGet("{id:guid}/download")]public async Task<IActionResult> Download(Guid id,CancellationToken ct){var d=await Access(id,ct);if(!await storage.ExistsAsync(d.StorageKey,ct))return Problem(statusCode:404,title:"Sandbox file is no longer available.");audit.Record("DocumentDownloaded",nameof(MemberDocument),id);await db.SaveChangesAsync(ct);return File(await storage.DownloadAsync(d.StorageKey,ct),d.MimeType,d.OriginalFileName);}
 [HttpDelete("{id:guid}")]public async Task<IActionResult> Delete(Guid id,CancellationToken ct){var d=await Access(id,ct);if(d.Member.UserId!=user.UserId)throw new RuleException("Only the owning member can remove this file.",403);d.IsDeleted=true;audit.Record("DocumentDeleted",nameof(MemberDocument),id);await db.SaveChangesAsync(ct);await storage.DeleteAsync(d.StorageKey,ct);return NoContent();}
 [Authorize(Policy=Policies.Documents),HttpPost("/api/admin/documents/{id:guid}/approve")]public Task<IActionResult> Approve(Guid id,ReviewRequest r,CancellationToken ct)=>Review(id,true,r,ct);
 [Authorize(Policy=Policies.Documents),HttpPost("/api/admin/documents/{id:guid}/reject")]public Task<IActionResult> Reject(Guid id,ReviewRequest r,CancellationToken ct)=>Review(id,false,r,ct);
 async Task<IActionResult> Review(Guid id,bool approved,ReviewRequest r,CancellationToken ct){await using var tx=await db.Database.BeginTransactionAsync(ct);var d=await db.Documents.Include(x=>x.Member).SingleOrDefaultAsync(x=>x.Id==id,ct)??throw new RuleException("Document not found.",404);if(d.Status!=DocumentStatus.PendingReview)throw new RuleException("Document already reviewed.",409);var before=d.Status;d.Status=DocumentRules.Reviewed(approved,d.ExpiryDate,clock.GetUtcNow().UtcDateTime);d.RejectionReason=r.Reason;d.ReviewedBy=user.UserId;d.ReviewedUtc=clock.GetUtcNow().UtcDateTime;db.Add(new DocumentReviewHistory{MemberDocumentId=id,PreviousStatus=before,NewStatus=d.Status,ReviewedBy=user.UserId,Notes=r.Reason});audit.Record("Document"+d.Status,nameof(MemberDocument),id);notifications.Enqueue(d.Member.UserId,approved?"document-approved":"document-rejected");await db.SaveChangesAsync(ct);await tx.CommitAsync(ct);await notifications.DispatchAsync(ct);return NoContent();}
}
