namespace Tga.Domain;

public abstract class Entity { public Guid Id { get; set; } = Guid.NewGuid(); public DateTime CreatedUtc { get; set; } = DateTime.UtcNow; }
public abstract class VersionedEntity : Entity { public Guid Version { get; set; } = Guid.NewGuid(); }
public enum MembershipStatus { Pending, Active, Expiring, Expired, Suspended, Cancelled, Rejected }
public enum DocumentStatus { Uploaded, PendingReview, Approved, Rejected, Expired, Replaced }
public enum PaymentStatus { Created, Pending, Paid, Failed, Cancelled, Refunded, PartiallyRefunded }
public enum AttemptStatus { InProgress, Submitted, Passed, Failed, Abandoned }
public enum QuestionType { SingleChoice, MultipleChoice, TrueFalse }
public class MemberProfile : VersionedEntity {
 public string UserId { get; set; } = ""; public string MembershipNumber { get; set; } = "";
 public string FirstName { get; set; } = ""; public string LastName { get; set; } = ""; public string PreferredName { get; set; } = "";
 public string Email { get; set; } = ""; public string MobileNumber { get; set; } = ""; public DateTime? DateOfBirth { get; set; }
 public string IdentifierPlaceholder { get; set; } = ""; public string Address { get; set; } = ""; public string City { get; set; } = "";
 public string Province { get; set; } = ""; public string PostalCode { get; set; } = ""; public string ProfileStatus { get; set; } = "Pending";
 public DateTime UpdatedUtc { get; set; } public DateTime? LastReviewedUtc { get; set; }
}
public class MembershipPlan : Entity { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public decimal JoiningFee { get; set; } public decimal AnnualFee { get; set; } public bool IsActive { get; set; } = true; public int DurationMonths { get; set; } = 12; }
public class Membership : VersionedEntity {
 public Guid MemberId { get; set; } public MemberProfile Member { get; set; } = null!; public Guid MembershipPlanId { get; set; } public MembershipPlan Plan { get; set; } = null!;
 public DateTime? StartDate { get; set; } public DateTime? EndDate { get; set; } public MembershipStatus Status { get; set; }
 public string RenewalStatus { get; set; } = "NotRequested"; public bool AutoRenewEnabled { get; set; } public Guid? LastPaymentId { get; set; } public DateTime UpdatedUtc { get; set; }
}
public class MembershipApplication : VersionedEntity { public Guid MemberId { get; set; } public Guid MembershipPlanId { get; set; } public string Status { get; set; } = "Pending"; public DateTime SubmittedUtc { get; set; } public DateTime? ReviewedUtc { get; set; } public string? ReviewedByUserId { get; set; } public string? RejectionReason { get; set; } public string? Notes { get; set; } }
public class MembershipStatusHistory : Entity { public Guid MembershipId { get; set; } public MembershipStatus PreviousStatus { get; set; } public MembershipStatus NewStatus { get; set; } public string ChangedBy { get; set; } = ""; public string Reason { get; set; } = ""; public DateTime ChangedUtc { get; set; } }
public class DocumentType : Entity { public string Name { get; set; } = ""; public string Description { get; set; } = ""; public bool IsRequired { get; set; } public bool RequiresExpiryDate { get; set; } public string AllowedMimeTypes { get; set; } = "application/pdf,image/jpeg,image/png"; public long MaxSizeBytes { get; set; } = 5242880; public bool IsActive { get; set; } = true; }
public class MemberDocument : VersionedEntity { public Guid MemberId { get; set; } public MemberProfile Member { get; set; } = null!; public Guid DocumentTypeId { get; set; } public DocumentType Type { get; set; } = null!; public string OriginalFileName { get; set; } = ""; public string StorageKey { get; set; } = ""; public string MimeType { get; set; } = ""; public long SizeBytes { get; set; } public string Checksum { get; set; } = ""; public string StorageProvider { get; set; } = "Demo"; public DocumentStatus Status { get; set; } = DocumentStatus.PendingReview; public DateTime UploadedUtc { get; set; } public DateTime? ReviewedUtc { get; set; } public string? ReviewedBy { get; set; } public string? RejectionReason { get; set; } public DateTime? ExpiryDate { get; set; } public bool IsDeleted { get; set; } }
public class DocumentReviewHistory : Entity { public Guid MemberDocumentId { get; set; } public DocumentStatus PreviousStatus { get; set; } public DocumentStatus NewStatus { get; set; } public string ReviewedBy { get; set; } = ""; public string Notes { get; set; } = ""; }
public class Assessment : VersionedEntity { public string Title { get; set; } = ""; public string Description { get; set; } = ""; public string Instructions { get; set; } = "Demo only; non-accredited."; public decimal PassPercentage { get; set; } = 80; public int? TimeLimitMinutes { get; set; } public int? MaxAttempts { get; set; } = 3; public bool RandomizeQuestions { get; set; } public bool IsActive { get; set; } = true; public bool IsAccredited { get; set; } public DateTime UpdatedUtc { get; set; } public List<Question> Questions { get; set; } = []; }
public class Question : Entity { public Guid AssessmentId { get; set; } public string QuestionText { get; set; } = ""; public QuestionType QuestionType { get; set; } public int Points { get; set; } = 1; public int SortOrder { get; set; } public bool IsActive { get; set; } = true; public List<QuestionOption> Options { get; set; } = []; }
public class QuestionOption : Entity { public Guid QuestionId { get; set; } public string Text { get; set; } = ""; public bool IsCorrect { get; set; } public int SortOrder { get; set; } }
public class AssessmentAttempt : VersionedEntity { public Guid AssessmentId { get; set; } public Assessment Assessment { get; set; } = null!; public Guid MemberId { get; set; } public MemberProfile Member { get; set; } = null!; public DateTime StartedUtc { get; set; } public DateTime? SubmittedUtc { get; set; } public int Score { get; set; } public decimal Percentage { get; set; } public bool Passed { get; set; } public AttemptStatus Status { get; set; } public string QuestionSnapshotJson { get; set; } = "[]"; public decimal PassPercentage { get; set; } public int? TimeLimitMinutes { get; set; } public List<AssessmentAnswer> Answers { get; set; } = []; }
public class AssessmentAnswer : Entity { public Guid AttemptId { get; set; } public Guid QuestionId { get; set; } public string SelectedAnswer { get; set; } = "[]"; public int AwardedPoints { get; set; } }
public class Certificate : Entity { public Guid MemberId { get; set; } public Guid AssessmentAttemptId { get; set; } public string CertificateNumber { get; set; } = ""; public DateTime IssuedUtc { get; set; } public DateTime? ExpiresUtc { get; set; } public string CertificateType { get; set; } = "Demo / non-accredited"; public string Status { get; set; } = "Issued"; }
public class PaymentTransaction : VersionedEntity { public Guid MemberId { get; set; } public MemberProfile Member { get; set; } = null!; public Guid? MembershipId { get; set; } public string PaymentType { get; set; } = "AnnualMembership"; public string Provider { get; set; } = "Mock"; public string? ProviderReference { get; set; } public string MerchantReference { get; set; } = Guid.NewGuid().ToString("N"); public decimal Amount { get; set; } public string Currency { get; set; } = "ZAR"; public PaymentStatus Status { get; set; } public DateTime? PaidUtc { get; set; } public DateTime? FailedUtc { get; set; } public string? FailureReason { get; set; } }
public class PaymentWebhookEvent : Entity { public string Provider { get; set; } = ""; public string ProviderEventId { get; set; } = ""; public string PayloadHash { get; set; } = ""; public DateTime ReceivedUtc { get; set; } public DateTime? ProcessedUtc { get; set; } public string ProcessingStatus { get; set; } = "Received"; }
public class Refund : VersionedEntity { public Guid PaymentTransactionId { get; set; } public decimal Amount { get; set; } public string Reason { get; set; } = ""; public string Status { get; set; } = "Requested"; public string RequestedBy { get; set; } = ""; public string? ApprovedBy { get; set; } public string? ProviderReference { get; set; } public DateTime? CompletedUtc { get; set; } }
public class NotificationTemplate : Entity { public string TemplateKey { get; set; } = ""; public string Content { get; set; } = ""; }
public class NotificationLog : Entity { public string RecipientUserId { get; set; } = ""; public string Channel { get; set; } = "Email"; public string TemplateKey { get; set; } = ""; public string DestinationMasked { get; set; } = "***"; public string Status { get; set; } = "Recorded"; public string Provider { get; set; } = "Console"; public string? ProviderMessageId { get; set; } public DateTime? SentUtc { get; set; } public DateTime? FailedUtc { get; set; } public string? ErrorSummary { get; set; } }
public class OtpChallenge : VersionedEntity { public string UserId { get; set; } = ""; public string Purpose { get; set; } = ""; public string CodeHash { get; set; } = ""; public DateTime ExpiresUtc { get; set; } public int Attempts { get; set; } public int MaxAttempts { get; set; } = 5; public DateTime? ConsumedUtc { get; set; } }
public class AuditEvent : Entity { public DateTime TimestampUtc { get; set; } public string? ActorUserId { get; set; } public string ActorRole { get; set; } = ""; public string Action { get; set; } = ""; public string EntityType { get; set; } = ""; public string EntityId { get; set; } = ""; public string? PreviousStateJson { get; set; } public string? NewStateJson { get; set; } public string CorrelationId { get; set; } = ""; public string? IpAddress { get; set; } public string? UserAgent { get; set; } }
public class PolicyDocument : Entity { public string Type { get; set; } = ""; public string Version { get; set; } = "demo-1"; public DateTime EffectiveDate { get; set; } public string Content { get; set; } = "Placeholder sandbox policy: use fictional data only."; public bool IsActive { get; set; } = true; }
public class UserPolicyAcceptance : Entity { public string UserId { get; set; } = ""; public Guid PolicyDocumentId { get; set; } public DateTime AcceptedUtc { get; set; } public string? IpAddress { get; set; } }
public class RefreshSession : VersionedEntity { public string UserId { get; set; } = ""; public string TokenHash { get; set; } = ""; public Guid FamilyId { get; set; } = Guid.NewGuid(); public DateTime ExpiresUtc { get; set; } public DateTime? RevokedUtc { get; set; } }
public class OutboxMessage : Entity { public string UserId { get; set; } = ""; public string TemplateKey { get; set; } = ""; public DateTime? ProcessedUtc { get; set; } public int Attempts { get; set; } }
