import {test} from 'node:test';
import assert from 'node:assert/strict';
import {createDemoApi,seedDemo,addMonths,DEMO_ACCOUNTS,STORE_KEY} from '../src/demo-api.js';
function memory(){const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
function setup(){const storage=memory(),sessionStorage=memory();let i=100;const options={storage,sessionStorage,now:()=> '2026-09-08T12:00:00.000Z',id:()=>`00000000-${String(i++).padStart(4,'0')}-4000-8000-000000000000`};return {api:createDemoApi(options),options};}
async function login(api,role='member'){const u=DEMO_ACCOUNTS.find(u=>u.role===role);return api.login(u.email,u.password);}
test('seed has complete fictional scenarios',()=>{const s=seedDemo('2026-09-08T12:00:00Z');assert.equal(s.members.length,50);assert.equal(s.documents.length,64);assert.equal(s.attempts.length,24);assert.equal(s.payments.length,40);assert.equal(s.users.length,9);assert.equal(s.members[0].endDate,'2026-09-29T12:00:00.000Z');});
test('annual dates clamp leap day',()=>{assert.equal(addMonths('2024-02-29T12:00:00Z'),'2025-02-28T12:00:00.000Z');});
test('all public demo credentials sign in with distinct roles',async()=>{const {api}=setup();for(const u of DEMO_ACCOUNTS)assert.equal((await api.login(u.email,u.password)).id,u.id);await assert.rejects(api.login('admin@tga.co.za','wrong'));});
test('profile changes persist through logout and reload',async()=>{const {api,options}=setup();await login(api);await api.updateProfile({firstName:'Demo','surname':'Changed',mobile:'000',province:'Gauteng',address:'Fictional'});await api.logout();const next=createDemoApi(options);await login(next);assert.equal((await next.snapshot()).profile.name,'Demo Changed');});
test('register creates a usable login and pending application',async()=>{const {api}=setup();const r=await api.register({email:'applicant@example.com',firstName:'Fictional',surname:'Applicant',consent:'on',membership:'Annual membership'});await api.login(r.email,r.password);assert.equal((await api.snapshot()).profile.status,'Pending review');await assert.rejects(api.register({email:r.email,firstName:'X',surname:'Y',consent:'on'}));});
test('membership approval/rejection saves history and notifies member',async()=>{const {api}=setup();await login(api,'admin');await api.changeMembership('TGA-2026-1047','Rejected','Demo incomplete application');let s=await api.snapshot();assert.equal(s.members.find(m=>m.id==='TGA-2026-1047').status,'Rejected');await api.changeMembership('TGA-2026-1047','Pending review','Reopen');await api.changeMembership('TGA-2026-1047','Active','Demo approval');s=await api.snapshot();assert.equal(s.history.filter(h=>h.memberId==='TGA-2026-1047').length,3);assert.ok(s.notifications.some(n=>n.title==='membership-approved'));});
test('member cannot approve members or documents',async()=>{const {api}=setup();await login(api);await assert.rejects(api.changeMembership('TGA-2026-1047','Active','No'));await assert.rejects(api.reviewDocument('doc-3',true,'No'));});
test('finance cannot change assessment settings',async()=>{const {api}=setup();await login(api,'finance');await assert.rejects(api.configureAssessment('portal-foundation',{passMark:1,maxAttempts:1,timeLimitMinutes:null}));assert.deepEqual((await api.snapshot()).assessments,[]);});
test('support cannot view uploaded documents or export personal register',async()=>{const {api}=setup();await login(api,'support');await assert.rejects(api.document('doc-3'));await assert.rejects(api.exportMembers());assert.deepEqual((await api.snapshot()).documents,[]);});
test('member cannot see another member document',async()=>{const {api}=setup();await login(api);await assert.rejects(api.document('doc-5'));});
test('upload validates extension MIME size and persists metadata',async()=>{const {api}=setup();await login(api);await assert.rejects(api.upload({name:'bad.exe',type:'Other',mime:'application/pdf',sizeBytes:10}));await assert.rejects(api.upload({name:'bad.pdf',type:'Other',mime:'image/png',sizeBytes:10}));await assert.rejects(api.upload({name:'big.pdf',type:'Other',mime:'application/pdf',sizeBytes:6000000}));const d=await api.upload({name:'demo.pdf',type:'Other',mime:'application/pdf',sizeBytes:12});assert.equal(d.status,'In review');assert.equal((await api.snapshot()).documents.length,5);});
test('verifier decision appears for member and records actor',async()=>{const {api}=setup();await login(api,'verifier');await api.reviewDocument('doc-3',true,'Clear fictional sample');await login(api);assert.equal((await api.snapshot()).documents.find(d=>d.id==='doc-3').status,'Approved');await login(api,'admin');assert.ok((await api.snapshot()).audit.some(a=>a.actor==='Demo Document Verifier'&&a.action==='Document Approved'));});
test('expired document receives Expired decision',async()=>{const {api}=setup();await login(api);const d=await api.upload({name:'demo.pdf',type:'Other',mime:'application/pdf',sizeBytes:12,expiryDate:'2026-01-01'});await login(api,'verifier');await api.reviewDocument(d.id,true,'Demo expired');assert.equal((await api.snapshot()).documents.find(x=>x.id===d.id).status,'Expired');});
test('assessment DTO excludes answer keys and scoring is persisted',async()=>{const {api}=setup();await login(api);const a=await api.startAssessment('portal-foundation');assert.ok(a.questions.every(q=>!('correct'in q)));await assert.rejects(api.submitAssessment(a.id,{}));const result=await api.submitAssessment(a.id,Object.fromEntries(a.questions.map((q,i)=>[q.id,[1,1,1,0,1][i]])));assert.equal(result.percentage,100);assert.equal(result.passed,true);await assert.rejects(api.submitAssessment(a.id,{}));});
test('assessment max attempts is enforced',async()=>{const {api}=setup();await login(api);for(let i=0;i<2;i++){const a=await api.startAssessment('portal-foundation');await api.submitAssessment(a.id,Object.fromEntries(a.questions.map(q=>[q.id,0])));}await assert.rejects(api.startAssessment('portal-foundation'),/Maximum/);});
test('in-progress attempt keeps original pass mark after edit',async()=>{const {api}=setup();await login(api);const a=await api.startAssessment('portal-foundation');await login(api,'assessor');await api.configureAssessment('portal-foundation',{passMark:10,maxAttempts:5,timeLimitMinutes:null});await login(api);const resumed=await api.startAssessment('portal-foundation');assert.equal(resumed.id,a.id);assert.equal(resumed.passMark,80);});
test('successful mock payment renews exactly once',async()=>{const {api}=setup();await login(api);const before=(await api.snapshot()).profile.endDate;const p=await api.checkout();assert.equal(p.amount,750);await api.completePayment(p.id,'Paid');await api.completePayment(p.id,'Paid');const s=await api.snapshot();assert.equal(s.profile.endDate,addMonths(before));assert.equal(s.payments.filter(x=>x.id===p.id&&x.status==='Paid').length,1);});
test('failed/cancelled mock payment does not renew and allows retry',async()=>{const {api}=setup();await login(api);const before=(await api.snapshot()).profile.endDate;const p=await api.checkout();await api.completePayment(p.id,'Failed');assert.equal((await api.snapshot()).profile.endDate,before);const retry=await api.checkout();assert.notEqual(retry.id,p.id);await api.completePayment(retry.id,'Cancelled');assert.equal((await api.snapshot()).profile.endDate,before);});
test('pending member payment does not bypass approval',async()=>{const {api}=setup();await api.login('pending@tga.example','demo123');const p=await api.checkout();await api.completePayment(p.id,'Paid');assert.equal((await api.snapshot()).profile.status,'Pending review');});
test('mock refund is finance-only and cannot repeat',async()=>{const {api}=setup();await login(api);await assert.rejects(api.refund('payment-1','Test'));await login(api,'finance');await api.refund('payment-1','Demo refund');await assert.rejects(api.refund('payment-1','Again'));assert.equal((await api.snapshot()).payments.find(p=>p.id==='payment-1').status,'Refunded');});
test('admin reset restores fixtures and is audited',async()=>{const {api}=setup();await login(api);await assert.rejects(api.reset());await login(api,'admin');await api.reset();const s=await api.snapshot();assert.equal(s.members.length,50);assert.ok(s.audit.some(a=>a.action==='Demo reset'));});
test('corrupt storage and unavailable writes show warning',async()=>{const storage={getItem:()=>'{',setItem:()=>{throw Error('quota');}};const api=createDemoApi({storage,sessionStorage:memory()});await login(api);assert.ok((await api.snapshot()).storageWarning);});
test('session survives page reload and logout clears it',async()=>{const {api,options}=setup();await login(api);const reloaded=createDemoApi(options);assert.equal((await reloaded.session()).role,'member');await reloaded.logout();assert.equal(await createDemoApi(options).session(),null);});
