using System.Net;
using System.Net.Http.Headers;
using System.Net.Http.Json;
using System.Text.Json;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.EntityFrameworkCore;
using Tga.Domain;
using Tga.Infrastructure.Persistence;
namespace Tga.IntegrationTests;
public class ApiFactory : WebApplicationFactory<Program> {
 public readonly string Root=Path.Combine(Path.GetTempPath(),"tga-tests-"+Guid.NewGuid().ToString("N"));
 protected override void ConfigureWebHost(IWebHostBuilder builder){Directory.CreateDirectory(Root);builder.UseEnvironment("Development");builder.ConfigureAppConfiguration((_,c)=>c.AddInMemoryCollection(new Dictionary<string,string?>{{"TGA_DATA_MODE","Demo"},{"TGA_PAYMENT_MODE","Mock"},{"ConnectionStrings:Demo","Data Source="+Path.Combine(Root,"test.db")},{"Storage:Path",Path.Combine(Root,"documents")},{"Jwt:Key",Convert.ToBase64String(System.Security.Cryptography.RandomNumberGenerator.GetBytes(48))},{"AllowedOrigins:0","http://localhost:5173"}}));}
}
public class ApiTests(ApiFactory factory) : IClassFixture<ApiFactory> {
 async Task<HttpClient> Login(string email="member@tga.co.za",string password="demo123"){var client=factory.CreateClient();client.DefaultRequestHeaders.Add("Origin","http://localhost:5173");var response=await client.PostAsJsonAsync("/api/auth/login",new{email,password});Assert.Equal(HttpStatusCode.OK,response.StatusCode);var body=await response.Content.ReadFromJsonAsync<JsonElement>();client.DefaultRequestHeaders.Authorization=new AuthenticationHeaderValue("Bearer",body.GetProperty("accessToken").GetString());return client;}
 static async Task<JsonElement> Json(HttpClient c,string path){var r=await c.GetAsync(path);Assert.True(r.IsSuccessStatusCode,await r.Content.ReadAsStringAsync());return await r.Content.ReadFromJsonAsync<JsonElement>();}
 [Fact]public async Task HealthAndSwagger(){var c=factory.CreateClient();Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/health/ready")).StatusCode);Assert.Equal(HttpStatusCode.OK,(await c.GetAsync("/swagger/v1/swagger.json")).StatusCode);}
 [Fact]public async Task AnonymousCannotReadMemberProfile(){var r=await factory.CreateClient().GetAsync("/api/me/profile");Assert.Equal(HttpStatusCode.Unauthorized,r.StatusCode);Assert.Contains("application/problem+json",r.Content.Headers.ContentType!.ToString());Assert.True(r.Headers.Contains("X-Correlation-ID"));}
 [Fact]public async Task RegisterLoginAndUpdateProfile(){var c=factory.CreateClient();var plans=await Json(c,"/api/membership-plans");var policies=await Json(c,"/api/policies");var email="demo-"+Guid.NewGuid().ToString("N")+"@example.com";var response=await c.PostAsJsonAsync("/api/auth/register",new{email,password="DemoPassword12!",firstName="Fictional",lastName="Applicant",planId=plans[0].GetProperty("id").GetGuid(),policyIds=policies.EnumerateArray().Select(x=>x.GetProperty("id").GetGuid()).ToArray()});Assert.Equal(HttpStatusCode.Created,response.StatusCode);var member=await Login(email,"DemoPassword12!");Assert.Equal("Fictional",(await Json(member,"/api/me/profile")).GetProperty("firstName").GetString());Assert.Equal(HttpStatusCode.NoContent,(await member.PatchAsJsonAsync("/api/me/profile",new{firstName="Updated",lastName="Applicant",mobileNumber="000",province="Gauteng",address="Fictional only"})).StatusCode);Assert.Equal("Updated",(await Json(member,"/api/me/profile")).GetProperty("firstName").GetString());}
 [Fact]public async Task AdminDashboardAndPagination(){var c=await Login("admin@tga.co.za","admin123");var dashboard=await Json(c,"/api/admin/dashboard");Assert.True(dashboard.GetProperty("totalMembers").GetInt32()>=50);var page=await Json(c,"/api/admin/members?pageSize=5");Assert.Equal(5,page.GetProperty("items").GetArrayLength());}
 [Fact]public async Task MembershipApprovalAndAudit(){var admin=await Login("admin@tga.co.za","admin123");var id=DemoDataSeeder.Id("membership-TGA-2026-1047");Assert.Equal(HttpStatusCode.NoContent,(await admin.PostAsJsonAsync($"/api/admin/memberships/{id}/approve",new{reason="Fictional application approved"})).StatusCode);var pending=await Login("pending@tga.example");Assert.Equal("Active",(await Json(pending,"/api/me/membership")).GetProperty("status").GetString());Assert.Contains("MembershipActive",(await Json(admin,"/api/admin/audit?pageSize=100")).ToString());}
 [Fact]public async Task MemberCannotApproveMembershipOrDocument(){var c=await Login();Assert.Equal(HttpStatusCode.Forbidden,(await c.PostAsJsonAsync($"/api/admin/memberships/{Guid.NewGuid()}/approve",new{reason="No"})).StatusCode);Assert.Equal(HttpStatusCode.Forbidden,(await c.PostAsJsonAsync($"/api/admin/documents/{Guid.NewGuid()}/approve",new{reason="No"})).StatusCode);}
 [Fact]public async Task FinanceCannotEditAssessment(){var c=await Login("finance@tga.example");Assert.Equal(HttpStatusCode.Forbidden,(await c.PostAsJsonAsync("/api/admin/assessments",new{title="Demo",description="Demo"})).StatusCode);}
 [Fact]public async Task PrivateUploadReviewAndDownload(){var c=await Login();var types=await Json(c,"/api/documents/types");using var form=new MultipartFormDataContent();var bytes=new ByteArrayContent("%PDF-1.4\nDEMO SAMPLE\n%%EOF"u8.ToArray());bytes.Headers.ContentType=new MediaTypeHeaderValue("application/pdf");form.Add(bytes,"file","demo.pdf");form.Add(new StringContent(types[0].GetProperty("id").GetString()!),"documentTypeId");var r=await c.PostAsync("/api/documents",form);Assert.Equal(HttpStatusCode.Created,r.StatusCode);var id=(await r.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.OK,(await c.GetAsync($"/api/documents/{id}/download")).StatusCode);var other=await Login("expired@tga.example");Assert.Equal(HttpStatusCode.NotFound,(await other.GetAsync($"/api/documents/{id}/download")).StatusCode);var verifier=await Login("verifier@tga.example");Assert.Equal(HttpStatusCode.NoContent,(await verifier.PostAsJsonAsync($"/api/admin/documents/{id}/approve",new{reason="Demo verified"})).StatusCode);Assert.Equal("Approved",(await Json(c,$"/api/documents/{id}")).GetProperty("status").GetString());}
 [Fact]public async Task SpoofedUploadRejected(){var c=await Login();var types=await Json(c,"/api/documents/types");using var form=new MultipartFormDataContent();var bytes=new ByteArrayContent("executable or fake"u8.ToArray());bytes.Headers.ContentType=new MediaTypeHeaderValue("application/pdf");form.Add(bytes,"file","fake.pdf");form.Add(new StringContent(types[0].GetProperty("id").GetString()!),"documentTypeId");Assert.Equal(HttpStatusCode.BadRequest,(await c.PostAsync("/api/documents",form)).StatusCode);}
 [Fact]public async Task AssessmentScoringHidesKeysAndRejectsRepeatSubmission(){var c=await Login();var assessmentId=DemoDataSeeder.Id("portal-foundation");var r=await c.PostAsync($"/api/assessments/{assessmentId}/attempts",null);Assert.Equal(HttpStatusCode.OK,r.StatusCode);var a=await r.Content.ReadFromJsonAsync<JsonElement>();Assert.DoesNotContain("correct",a.ToString(),StringComparison.OrdinalIgnoreCase);var answers=new Dictionary<Guid,Guid[]>();using(var scope=factory.Services.CreateScope()){var db=scope.ServiceProvider.GetRequiredService<TgaDbContext>();foreach(var q in await db.Set<Question>().Include(x=>x.Options).Where(x=>x.AssessmentId==assessmentId).ToListAsync())answers[q.Id]=q.Options.Where(x=>x.IsCorrect).Select(x=>x.Id).ToArray();}var id=a.GetProperty("id").GetGuid();Assert.Equal(HttpStatusCode.NoContent,(await c.PutAsJsonAsync($"/api/assessment-attempts/{id}/answers",new{answers})).StatusCode);var result=await c.PostAsync($"/api/assessment-attempts/{id}/submit",null);Assert.Equal(HttpStatusCode.OK,result.StatusCode);Assert.Equal(100,(await result.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("percentage").GetDecimal());Assert.Equal(HttpStatusCode.Conflict,(await c.PostAsync($"/api/assessment-attempts/{id}/submit",null)).StatusCode);}
 [Fact]public async Task MockPaymentIsIdempotentAndFailureDoesNotRenew(){var c=await Login();var before=(await Json(c,"/api/me/membership")).GetProperty("endDate").GetDateTime();var checkout=await c.PostAsJsonAsync("/api/payments/checkout",new{paymentType="Renewal"});var id=(await checkout.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("paymentId").GetGuid();Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync($"/api/payments/{id}/mock-complete",new{success=false})).StatusCode);Assert.Equal(before,(await Json(c,"/api/me/membership")).GetProperty("endDate").GetDateTime());checkout=await c.PostAsJsonAsync("/api/payments/checkout",new{paymentType="Renewal"});id=(await checkout.Content.ReadFromJsonAsync<JsonElement>()).GetProperty("paymentId").GetGuid();for(var i=0;i<2;i++)Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsJsonAsync($"/api/payments/{id}/mock-complete",new{success=true})).StatusCode);Assert.Equal(before.AddYears(1),(await Json(c,"/api/me/membership")).GetProperty("endDate").GetDateTime());using var scope=factory.Services.CreateScope();var db=scope.ServiceProvider.GetRequiredService<TgaDbContext>();Assert.Equal(1,await db.Set<PaymentWebhookEvent>().CountAsync(x=>x.ProviderEventId=="mock-"+id.ToString("N")));}
 [Fact]public async Task LogoutRevokesAccessAndRefreshRequiresAllowedOrigin(){var c=await Login();Assert.Equal(HttpStatusCode.NoContent,(await c.PostAsync("/api/auth/logout",null)).StatusCode);Assert.Equal(HttpStatusCode.Unauthorized,(await c.GetAsync("/api/me/profile")).StatusCode);var bad=factory.CreateClient();bad.DefaultRequestHeaders.Add("Origin","https://untrusted.example");Assert.Equal(HttpStatusCode.Forbidden,(await bad.PostAsync("/api/auth/refresh",null)).StatusCode);}
 [Fact]public async Task SupportCannotDownloadDocuments(){var c=await Login("support@tga.example");Assert.Equal(HttpStatusCode.NotFound,(await c.GetAsync($"/api/documents/{DemoDataSeeder.Id("doc-1")}/download")).StatusCode);}
}
